### PR TITLE
Add version 70.4

### PR DESCRIPTION
**Pull request by elijahtsai**
To @JosephShenton @Aurther-Nadeem, Can you help us to test the m1 platform for v70.4(new version), thank you!!!!

Tested platform 

- [x] Intel platform 
- [ ] M1 platform

To @duraki 
1. I made a question in ada011a for whether or not to delete the shot image.
2. You forgot to add @Aurther-Nadeem to be a contributor.

### CODE REVIEW

**Comment by duraki** [comment]
Hi Elijah, thanks a lot for PR! And of course thanks for supporting v70.4. I can't speak for M1 but I will deff give it a try and test the new version, especially since I have some new design requests.

As for the image, I don't mind if you take it down, but I know I always give **STARS** to GH projects who has media and looks playful rather then just plain text (borrrriiiing) in the README file. So, yes, be free to remove the Terminal image, but just so you know if you have any other idea we can put it there instead. I've read users are more attracted to posts which contains a media of sort. And I can confirm that from myself (just look at my other repositories).

I think I've added @Aurther-Nadeem to the contrib but he didn't accept it yet. He should accept the invite.

**Comment by elijahtsai** [comment]
I think the media thing is **really** a good idea but the shot image are just not.... very suitable in the readme because GitHub doesn't have good render on it. We may need to think another ways for how to see the balance that with images or media and suit the formation. what do you think👍🏻

**Comment by elijahtsai** [comment]
@duraki Ha! I found the markdown language you used in your other repo [charles-keygen/README.md](https://github.com/duraki/charles-keygen/blob/master/README.md), and it looks awesome even on the phone screen. what do you think?????!!!!!!

**Comment by elijahtsai** [comment]
But I can't upload the banner image to Imgur so some preview can't display correctly, can you help me to upload banner.png to Imgur and tell me the new link.

**Comment by elijahtsai** [comment]
@Aurther-Nadeem  Is the script working on the m1 platform? I see you check the box then uncheck again???

**Comment by duraki** [comment]
@elijahtsai you don't need to register on Imgur to upload. But, here it is: https://i.imgur.com/4HeAd8j.png

**Pull request merged**
